exper = createTrials('AgRP_stress_day2-1', 'Conditioning_templates_2',... 
                    'cueL',500, 'grayL', 400, 'arenaL', 8000,...
                    'overlap',2, 'nWorlds', 52, 'stress',true,...
                    'movement', @moveWithQuadEncoder, 'experiment', @Trial_code,...
                    'transformation', @transformPerspectiveMex2,...
                        'cueList', {['CueDarkCircle'], ['CueLightRect']},...
                    'grayCue', {['CueGray']},...
                    'atrandom', true, 'shock', false, 'tiling', 4, 'save', true,...
                    'padding',false, 'rewarddelay', 0, 'startloc', [0,5,80,0]);

exper = createTrials('AgRP_stress_day2-2', 'Conditioning_templates_2',... 
                    'cueL',500, 'grayL', 400, 'arenaL', 8000,...
                    'overlap',2, 'nWorlds', 52, 'stress',true,...
                    'movement', @moveWithQuadEncoder, 'experiment', @Trial_code,...
                    'transformation', @transformPerspectiveMex2,...
                        'cueList', {['CueDarkCircle'], ['CueLightRect']},...
                    'grayCue', {['CueGray']},...
                    'atrandom', true, 'shock', false, 'tiling', 4, 'save', true,...
                    'padding',false, 'rewarddelay', 0, 'startloc', [0,5,80,0]);
                