exper = createTrials('190926_baseline_3', 'Conditioning_templates_3',... 
                    'cueL',450, 'grayL', 400, 'arenaL', 4000,...
                    'overlap',2, 'nWorlds', 86, 'stress',true,...
                    'movement', @moveWithQuadEncoder, 'experiment', @Trial_code,...
                    'transformation', @transformPerspectiveMex2,...
                        'cueList', {['CueStripe90'], ['CueCheckers']}, 'grayCue', {['CueGray']},...
                    'atrandom', true, 'shock', false, 'tiling', 1, 'save', true,...
                    'padding',false, 'rewarddelay', 0, 'startloc', [0,5,100,0]);
                    
exper = createTrials('190927_baseline_4', 'Conditioning_templates_3',... 
                    'cueL',450, 'grayL', 400, 'arenaL', 4000,...
                    'overlap',2, 'nWorlds', 86, 'stress',true,...
                    'movement', @moveWithQuadEncoder, 'experiment', @Trial_code,...
                    'transformation', @transformPerspectiveMex2,...
                        'cueList', {['CueStripe90'], ['CueCheckers']}, 'grayCue', {['CueGray']},...
                    'atrandom', true, 'shock', false, 'tiling', 1, 'save', true,...
                    'padding',false, 'rewarddelay', 0, 'startloc', [0,5,100,0]);

exper = createTrials('190928_baseline_5', 'Conditioning_templates_3',... 
                    'cueL',450, 'grayL', 400, 'arenaL', 4000,...
                    'overlap',2, 'nWorlds', 86, 'stress',true,...
                    'movement', @moveWithQuadEncoder, 'experiment', @Trial_code,...
                    'transformation', @transformPerspectiveMex2,...
                        'cueList', {['CueStripe90'], ['CueCheckers']}, 'grayCue', {['CueGray']},...
                    'atrandom', true, 'shock', false, 'tiling', 1, 'save', true,...
                    'padding',false, 'rewarddelay', 0, 'startloc', [0,5,100,0]);

exper = createTrials('190925_baseline_2', 'Conditioning_templates_3',... 
                    'cueL',450, 'grayL', 400, 'arenaL', 4000,...
                    'overlap',2, 'nWorlds', 86, 'stress',true,...
                    'movement', @moveWithQuadEncoder, 'experiment', @Trial_code,...
                    'transformation', @transformPerspectiveMex2,...
                        'cueList', {['CueStripe90'], ['CueCheckers']}, 'grayCue', {['CueGray']},...
                    'atrandom', true, 'shock', false, 'tiling', 1, 'save', true,...
                    'padding',false, 'rewarddelay', 0, 'startloc', [0,5,100,0]);